version: "2"
services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /export
    environment: 
      - "MINIO_ACCESS_KEY=ABC_ACCESS_KEY"
      - "MINIO_SECRET_KEY=SECRET_KEY_PASSWORD"
